-- DELETE * FROM albums

DELETE FROM albums CASCADE;
DELETE FROM artistfans CASCADE;
DELETE FROM artisTtags CASCADE;
DELETE FROM artists CASCADE;
DELETE FROM facebookobjects CASCADE;
DELETE FROM fans CASCADE;
DELETE FROM lastfmartists CASCADE;
DELETE FROM similarartists CASCADE;
DELETE FROM tags CASCADE;